### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by daroczig** [evrone/toggl-python#31]
Hi,

First of all, thanks a ton for maintaining this package!

Do you have plans to update the very outdated pypi release at https://pypi.org/project/toggl-python/?

Thanks,
Gergely

**Comment by nifadyev** [comment]
Hello @daroczig , new package version has just been released.
If you're still using the package, could you please share your experience and give feedback? It would help a lot to improve the package.

**Comment by daroczig** [comment]
Sorry, I don't have much feedback -- decided to roll my own few-liner helper function for the small set of Toggl API endpoints I need, and did not take on `toggl-python` after all in production as I was not sure about the status of the project. It's great to see now that it's actively developed and all the updates in the other tickets :raised_hands:

**Comment by nifadyev** [comment]
Understood, thank you @daroczig . You can watch for new releases and I hope the project will suit your needs one day.
Closing the issue as completed.

**Comment by daroczig** [comment]
For sure, I'll keep an eye on the project -- thanks for your hard work on it :bow:
