### ISSUE TITLE
Implement Project entity

### ISSUE THREAD

**Issue by ivlevdenis** [evrone/toggl-python#4]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md

**Comment by nifadyev** [comment]
According to [migration guide](https://engineering.toggl.com/docs/additional/v8_migration_guide/index.html), `Projects` related endpoints are moved into `/me` and /workspace/<id>/` paths. So related logic and entity structure should be refactored.

**Comment by nifadyev** [comment]
Rough plan:

- Necessary endpoints (available on free plan):
  - GET `/me/projects`
  - GET `/me/projects/paginated`
  - GET/POST/PATCH `{workspace_id}/projects`
  - GET/PUT/DELETE `{workspace_id}/projects/{project_id}`
- Cover new logic with tests and type annotations
