### ISSUE TITLE
Adapt Tasks related logic to API V9

### ISSUE THREAD

**Issue by ivlevdenis** [evrone/toggl-python#7]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/tasks.md

**Comment by nifadyev** [comment]
According to [migration guide](https://engineering.toggl.com/docs/additional/v8_migration_guide/index.html), `Tasks` related endpoints are moved into `/me` and `/workspace/<id>/projects/<id>/` paths. So related logic and entity structure should be refactored.

**Comment by nifadyev** [comment]
Closed because `Tasks` are available only on paid plan
