### ISSUE TITLE
Implement TimeEntry entity

### ISSUE THREAD

**Issue by ivlevdenis** [evrone/toggl-python#8]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md

**Comment by nifadyev** [comment]
Rough plan:

- Necessary endpoints (available on free plan):
	- GET `/me/time_entries`
	- GET `/me/time_entries/current`
	- GET `/me/time_entries/{time_entry_id}`
	- PATCH `/{workspace_id}/time_entries/{time_entry_ids}` - bulk editing
	- PUT/DELETE `/{workspace_id}/time_entries/{time_entry_id}`
	- PATCH `/{workspace_id}/time_entries/{time_entry_id}/stop`
	- GET `/{workspace_id}/time_entry_constraints`
- Cover new logic with tests and type annotations
