### ISSUE TITLE
Implement CurrentUser entity

### ISSUE THREAD

**Issue by ivlevdenis** [evrone/toggl-python#9]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/users.md

**Comment by nifadyev** [comment]
According to [migration guide](https://engineering.toggl.com/docs/additional/v8_migration_guide/index.html), most endpoints for current users is available at `/me` path. So `Users` related repository should be refactored

**Comment by nifadyev** [comment]
Rough plan:

- Add check for billing plan. Request and response fields set [depend on it](https://engineering.toggl.com/docs/#general-principles), as well as endpoints availability
- Write explicit note about using UTC timezone for datetime (until some type of package config with user timezone is implemented)
- Necessary endpoints (available on free plan):
  - GET/PUT `/me` - Returns details for the current user. Returns huge response, which requires a lot of `pydantic` schemas for mostly all `toggl` entities
  - GET `/me/clients`
  - GET `/me/features`
  - GET `/me/organizations`
  - GET `/me/projects`
  - GET `/me/projects/paginated`
  - GET `/me/tags`
  - GET `/me/web-timer`
  - GET `/me/workspaces`
  - GET/POST `/me/preferences`
  - GET/POST `/me/preferences/{client}`
- Cover new logic with tests and type annotations
